package ai.orchestree.backend

import ai.orchestree.backend.api.InMemoryConversationStore
import ai.orchestree.backend.channels.ChannelGateway
import ai.orchestree.backend.database.repositories.taskboard.TaskRepository
import ai.orchestree.backend.database.repositories.workforce.ProactiveCollaborationScopeRepository
import ai.orchestree.backend.intelligence.ContextResolver
import ai.orchestree.backend.intelligence.IntentCategory
import ai.orchestree.backend.intelligence.ManagementQueryEngine
import ai.orchestree.backend.modelrouter.ModelRouter
import ai.orchestree.backend.orchestration.OrchestrationEngine
import ai.orchestree.backend.orchestration.definitions.WorkflowDefinitions
import ai.orchestree.backend.webhooks.TelegramWebhookHandler
import ai.orchestree.backend.webhooks.WhatsAppWebhookHandler
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.io.File
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

class Fase3OmnichannelAndProactiveVerificationTest {

    private fun generateHmacSha256(data: String, key: String): String {
        val sha256Hmac = Mac.getInstance("HmacSHA256")
        val secretKey = SecretKeySpec(key.toByteArray(Charsets.UTF_8), "HmacSHA256")
        sha256Hmac.init(secretKey)
        val signedBytes = sha256Hmac.doFinal(data.toByteArray(Charsets.UTF_8))
        return "sha256=" + signedBytes.joinToString("") { "%02x".format(it) }
    }

    @Test
    fun testWhatsAppWebhook_SignatureAndChannelPipeline() = runBlocking {
        val appSecret = "secret_meta_app_key_123"
        val payload = """{"senderId":"628123456789","senderName":"Pak Hendra","messageText":"Halo apa produk terlaris minggu ini?","tenantId":"tenant-default"}"""
        val validSig = generateHmacSha256(payload, appSecret)

        val handler = WhatsAppWebhookHandler()
        val result = handler.processInboundWebhook(
            payload = payload,
            signatureHeader = validSig,
            appSecret = appSecret,
            defaultTenantId = "tenant-default"
        )

        assertTrue(result.verified, "WhatsApp webhook signature must be verified")
        assertNotNull(result.conversationId, "Conversation ID must be generated")
        assertNotNull(result.replyText, "Outbound reply must be generated by ChannelGateway")
        assertEquals("628123456789", result.senderId)

        // Invalid signature test
        val invalidResult = handler.processInboundWebhook(
            payload = payload,
            signatureHeader = "sha256=invalid_signature_hash_value",
            appSecret = appSecret
        )
        assertFalse(invalidResult.verified, "Invalid signature must be rejected")
    }

    @Test
    fun testTelegramWebhook_SecretTokenAndChannelPipeline() = runBlocking {
        val secretToken = "secret_telegram_auth_token_xyz"
        val payload = """{"senderId":"tg-987654","senderName":"Dewi Lestari","messageText":"Saya ingin menanyakan promo bulan ini","tenantId":"tenant-default"}"""

        val handler = TelegramWebhookHandler()
        val result = handler.processInboundWebhook(
            payload = payload,
            secretTokenHeader = secretToken,
            expectedSecretToken = secretToken,
            defaultTenantId = "tenant-default"
        )

        assertTrue(result.verified, "Telegram secret token must be verified")
        assertNotNull(result.conversationId)
        assertNotNull(result.replyText)

        // Invalid secret token test
        val invalidResult = handler.processInboundWebhook(
            payload = payload,
            secretTokenHeader = "wrong-token",
            expectedSecretToken = secretToken
        )
        assertFalse(invalidResult.verified, "Wrong secret token must be rejected")
    }

    @Test
    fun testProactiveCollaborationScope_FinancialIsolation() = runBlocking {
        val scopeRepo = ProactiveCollaborationScopeRepository.defaultInstance

        // Staff Sales Role -> Must be DEPARTMENT SCOPED and RESTRICTED from financial data
        val salesScope = scopeRepo.determineProactiveScope(
            staffId = "staff-sales-01",
            explicitJobLevel = "Sales Representative",
            explicitDepartment = "sales"
        )
        assertEquals("department_scoped", salesScope.scopeType)
        assertFalse(salesScope.hasFinancialAccess, "Sales staff must NOT have financial access")
        assertTrue(salesScope.financialDataRestricted, "Sales staff financial data must be restricted")
        assertNotNull(salesScope.collaboratingAiJobTitleIds)
        assertFalse(salesScope.collaboratingAiJobTitleIds!!.contains("finance"), "Sales AI collaboration scope must not include finance")

        // Executive / Owner Role -> EXECUTIVE FULL SUMMARY and FULL access
        val execScope = scopeRepo.determineProactiveScope(
            staffId = "staff-ceo-01",
            explicitJobLevel = "Chief Executive Officer / Direksi",
            explicitDepartment = "executive"
        )
        assertEquals("executive_full_summary", execScope.scopeType)
        assertTrue(execScope.hasFinancialAccess, "Executive must have financial access")
        assertFalse(execScope.financialDataRestricted, "Executive must not have financial restrictions")

        // ContextResolver test for Staff Daily Brief
        val salesBrief = ContextResolver.forStaffDailyBrief(
            staffId = "staff-sales-01",
            types = listOf("DAILY_BRIEF"),
            restrictToAiJobTitleIds = salesScope.collaboratingAiJobTitleIds
        )
        val hasCashFlow = salesBrief.any { str: String -> str.contains("Cash flow", ignoreCase = true) || str.contains("Finance", ignoreCase = true) }
        assertFalse(hasCashFlow, "Sales daily brief must NEVER leak cash flow or finance numbers")

        // Management Query Engine scope isolation
        val queryEngine = ManagementQueryEngine(ModelRouter())
        val financeQueryBySales = queryEngine.handleQuery(
            tenantId = "tenant-default",
            staffId = "staff-sales-01",
            staffProfile = null,
            queryText = "Berapa sisa kas dan saldo rekening bank kita?"
        )
        assertFalse(financeQueryBySales.allowed, "Query for cash/bank by sales staff must be disallowed")
        assertTrue(financeQueryBySales.responseText.contains("di luar cakupan", ignoreCase = true) || financeQueryBySales.responseText.contains("Direksi", ignoreCase = true))
    }

    @Test
    fun testInboundChannelMessage_TaskCreationWithChecklistsAndActivityLog() = runBlocking {
        val gateway = ChannelGateway()
        val taskRepo = TaskRepository.defaultInstance

        val result = gateway.handleInboundProactiveChannelMessage(
            tenantId = "tenant-default",
            channelType = "WHATSAPP",
            senderId = "628999999",
            senderName = "Hendra Supervisor",
            messageText = "buat task urgent siapkan materi presentasi klien besok",
            taskRepo = taskRepo
        )

        assertTrue(result.processed)
        assertEquals(IntentCategory.TASK_CREATION_COMMAND.name, result.intent)
        assertNotNull(result.taskId)
        assertNotNull(result.taskCreated)
        assertEquals("HIGH", result.taskCreated?.priority)

        // Verify checklists were generated
        val checklists = taskRepo.getChecklistsForTask(result.taskId!!)
        assertTrue(checklists.isNotEmpty(), "Checklists must be decomposed for Kanban task")

        // Verify activity log was recorded
        val logs = taskRepo.getActivityLogs(result.taskId!!)
        assertTrue(logs.isNotEmpty(), "Task activity log must be recorded")
    }

    @Test
    fun testChiefOfStaffBriefingWorkflow_5NodeDAGExecution() = runBlocking {
        val engine = OrchestrationEngine(modelRouter = ModelRouter())
        val wfDef = WorkflowDefinitions.ALL_WORKFLOWS.find { it.id == "wf-chief-of-staff-briefing" }
        assertNotNull(wfDef, "wf-chief-of-staff-briefing must be defined")
        assertEquals(5, wfDef!!.nodes.size, "wf-chief-of-staff-briefing must have exactly 5 nodes")

        val expectedNodeIds = listOf(
            "n1-aggregate-metrics",
            "n2-anomaly-detection",
            "n3-strategic-correlation",
            "n4-synthesize-briefing",
            "n5-distribute-channels"
        )
        assertEquals(expectedNodeIds, wfDef.nodes.map { it.nodeId })

        val execResult = engine.runWorkflow(
            tenantId = "tenant-default",
            workflowDefId = "wf-chief-of-staff-briefing",
            prompt = "Sintesis briefing eksekutif pagi ini"
        )

        assertEquals("COMPLETED", execResult.status, "Workflow run must complete")
        assertEquals(5, execResult.nodeRuns.size, "All 5 nodes must be executed")
    }

    @Test
    fun testSupabaseRealtimePublicationSchema() {
        val migrationFile = sequenceOf(
            File("db/migrations/V37__enable_supabase_realtime_publications.sql"),
            File("orchestreeai-backend-server/db/migrations/V37__enable_supabase_realtime_publications.sql"),
            File("/app/applet/orchestreeai-backend-server/db/migrations/V37__enable_supabase_realtime_publications.sql")
        ).firstOrNull { it.exists() }

        assertNotNull(migrationFile, "V37 migration must exist")
        val content = migrationFile!!.readText()
        assertTrue(content.contains("supabase_realtime"), "Must configure supabase_realtime publication")
        assertTrue(content.contains("conversations"), "Must include conversations table")
        assertTrue(content.contains("conversation_messages"), "Must include conversation_messages table")
        assertTrue(content.contains("tasks"), "Must include tasks table")
    }
}
