package ai.orchestree.backend

import ai.orchestree.backend.channels.ChannelGateway
import ai.orchestree.backend.channels.InboundMessage
import ai.orchestree.backend.config.AppConfig
import ai.orchestree.backend.database.repositories.analytics.AnalyticsRepository
import ai.orchestree.backend.database.repositories.modelrouter.LlmProviderEntity
import ai.orchestree.backend.database.repositories.modelrouter.ProviderRegistryRepository
import ai.orchestree.backend.generativestudio.GenerativeStudioService
import ai.orchestree.backend.modelrouter.LlmClient
import ai.orchestree.backend.modelrouter.LlmRequest
import ai.orchestree.backend.modelrouter.LlmResponse
import ai.orchestree.backend.modelrouter.ModelRouteRequest
import ai.orchestree.backend.modelrouter.ModelRouter
import ai.orchestree.backend.startup.FatalConfigurationException
import ai.orchestree.backend.startup.StartupValidator
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows

class Fase82ModelRouterFallbackPriorityVerificationTest {

    private lateinit var providerRepo: ProviderRegistryRepository
    private lateinit var mockOpenRouterClient: LlmClient
    private lateinit var mockGroqClient: LlmClient
    private lateinit var mockDeepSeekClient: LlmClient
    private lateinit var mockAnthropicClient: LlmClient
    private lateinit var mockGeminiClient: LlmClient
    private val executionLog = mutableListOf<String>()

    @BeforeEach
    fun setUp() {
        executionLog.clear()
        providerRepo = ProviderRegistryRepository()

        mockOpenRouterClient = object : LlmClient {
            override val providerId = "openrouter"
            override val providerName = "OpenRouter"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("OPENROUTER")
                return Result.success(
                    LlmResponse(
                        text = "Response generated by OpenRouter [claude-3.5-sonnet]",
                        totalTokens = 120,
                        modelUsed = "anthropic/claude-3.5-sonnet",
                        providerUsed = "openrouter",
                        durationMs = 150
                    )
                )
            }
        }

        mockGroqClient = object : LlmClient {
            override val providerId = "groq"
            override val providerName = "Groq Cloud"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("GROQ")
                return Result.success(
                    LlmResponse(
                        text = "Response generated by Groq [llama-3.3-70b-versatile]",
                        totalTokens = 110,
                        modelUsed = "llama-3.3-70b-versatile",
                        providerUsed = "groq",
                        durationMs = 45
                    )
                )
            }
        }

        mockDeepSeekClient = object : LlmClient {
            override val providerId = "deepseek"
            override val providerName = "DeepSeek AI"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("DEEPSEEK")
                return Result.success(
                    LlmResponse(
                        text = "Response generated by DeepSeek [deepseek-chat]",
                        totalTokens = 135,
                        modelUsed = "deepseek-chat",
                        providerUsed = "deepseek",
                        durationMs = 95
                    )
                )
            }
        }

        mockAnthropicClient = object : LlmClient {
            override val providerId = "anthropic"
            override val providerName = "Anthropic"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("ANTHROPIC")
                return Result.success(
                    LlmResponse(
                        text = "Response generated by Anthropic [claude-3-5-sonnet]",
                        totalTokens = 140,
                        modelUsed = "claude-3-5-sonnet-20241022",
                        providerUsed = "anthropic",
                        durationMs = 210
                    )
                )
            }
        }

        mockGeminiClient = object : LlmClient {
            override val providerId = "gemini"
            override val providerName = "Google Gemini"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("GEMINI")
                return Result.success(
                    LlmResponse(
                        text = "Response generated by Gemini",
                        totalTokens = 90,
                        modelUsed = "gemini-3.5-flash-lite",
                        providerUsed = "gemini",
                        durationMs = 120
                    )
                )
            }
        }
    }

    @Test
    fun testProviderRegistryRepositoryOrdersProvidersByFallbackPriority() {
        val providers = providerRepo.getLlmProvidersOrderedByFallbackPriority()
        assertTrue(providers.isNotEmpty(), "Active providers must not be empty")

        // First provider must be OPENROUTER (fallback_priority 1)
        val first = providers.first()
        assertEquals("OPENROUTER", first.providerCode.uppercase())
        assertEquals(1, first.fallbackPriority)

        // Providers must be strictly ascending by fallbackPriority
        val priorities = providers.map { it.fallbackPriority }
        assertEquals(priorities.sorted(), priorities, "Providers must be strictly sorted by fallback_priority ascending")

        // Verify Gemini is NEVER the top provider
        assertFalse(providers.first().providerCode.equals("gemini", ignoreCase = true), "Gemini must never be top provider")

        // Verify Image provider default is GPT_IMAGE_2
        val imgProvider = providerRepo.getActiveImageProvider()
        assertEquals("GPT_IMAGE_2", imgProvider.providerCode.uppercase())
        assertEquals("gpt-image-2", imgProvider.defaultModel)
    }

    @Test
    fun testStartupValidationFailsClosedWhenGeminiInDatabaseWithoutApiKey() = runBlocking {
        val validator = StartupValidator(shouldExitProcessOnFailure = false)
        val stubRepo = object : ProviderRegistryRepository() {
            override fun getAllActive(): List<LlmProviderEntity> = listOf(
                LlmProviderEntity(
                    id = "llm-unauth-gemini",
                    name = "Google Gemini Unofficial",
                    providerCode = "GEMINI",
                    apiBaseUrl = "https://generativelanguage.googleapis.com",
                    apiKeyEnv = "PATH",
                    priority = 1,
                    fallbackPriority = 1,
                    taskSpecialization = "general"
                ),
                LlmProviderEntity(
                    id = "llm-groq",
                    name = "Groq",
                    providerCode = "GROQ",
                    apiBaseUrl = "https://api.groq.com/openai/v1",
                    apiKeyEnv = "PATH",
                    priority = 2,
                    fallbackPriority = 2,
                    taskSpecialization = "fast"
                )
            )
            override fun getLlmProvidersOrderedByFallbackPriority(): List<LlmProviderEntity> = getAllActive()
        }

        val ex = assertThrows<FatalConfigurationException> {
            validator.verifyNoHardcodedProviderFallback(stubRepo)
        }
        assertTrue(ex.message!!.contains("Google Gemini terkonfigurasi sebagai prioritas 1"), "Must reject Gemini entry as priority 1")
    }

    @Test
    fun testUniversalPromptComposerRoutesToConfiguredFallbackPriorityProvider() = runBlocking {
        val router = ModelRouter(
            config = AppConfig(environment = "production"),
            providerRepo = providerRepo,
            customProviders = mapOf(
                "openrouter" to mockOpenRouterClient,
                "groq" to mockGroqClient,
                "deepseek" to mockDeepSeekClient,
                "anthropic" to mockAnthropicClient,
                "gemini" to mockGeminiClient
            )
        )

        // Critical Point 1: Universal Prompt Composer (Fase 82)
        val req = ModelRouteRequest(
            taskCategory = "UNIVERSAL_PROMPT_COMPOSER",
            prompt = "Tuliskan strategi peluncuran produk enterprise B2B",
            tenantId = "tenant-test-1"
        )
        val res = router.route(req)
        assertTrue(res.isSuccess)
        val response = res.getOrThrow()

        // Must NOT call Gemini
        assertFalse(executionLog.contains("GEMINI"), "Universal Prompt Composer must NEVER call Gemini")
        // Must call OpenRouter or Groq based on fallback_priority
        assertTrue(executionLog.contains("OPENROUTER") || executionLog.contains("GROQ"))
        assertTrue(response.providerUsed.lowercase() in listOf("openrouter", "groq"))
    }

    @Test
    fun testGenerativeStudioRoutesToConfiguredFallbackPriorityProvider() = runBlocking {
        val router = ModelRouter(
            config = AppConfig(environment = "production"),
            providerRepo = providerRepo,
            customProviders = mapOf(
                "openrouter" to mockOpenRouterClient,
                "groq" to mockGroqClient,
                "deepseek" to mockDeepSeekClient,
                "anthropic" to mockAnthropicClient,
                "gemini" to mockGeminiClient
            )
        )

        // Critical Point 2: Generative Studio (Fase 82)
        val studio = GenerativeStudioService(modelRouter = router)
        val campaign = studio.generateCampaignCreative(
            tenantId = "tenant-test-1",
            topic = "SaaS Cloud Management Platform",
            platform = "LinkedIn"
        )

        assertNotNull(campaign)
        assertTrue(campaign.title.contains("SaaS Cloud Management Platform"))
        // Verify Gemini was NEVER invoked
        assertFalse(executionLog.contains("GEMINI"), "Generative Studio must NEVER call Gemini")
        assertTrue(executionLog.contains("OPENROUTER") || executionLog.contains("GROQ"))
    }

    @Test
    fun testGenerateDesignDocumentAndImageUsesGptImage2NotGoogleImagen() = runBlocking {
        val imgProvider = providerRepo.getActiveImageProvider()
        assertEquals("GPT_IMAGE_2", imgProvider.providerCode.uppercase())
        assertEquals("gpt-image-2", imgProvider.defaultModel)
        assertFalse(imgProvider.providerCode.contains("imagen", ignoreCase = true))

        // Image provider list must prioritize GPT_IMAGE_2
        val imageProviders = providerRepo.getImageProviders()
        assertEquals("GPT_IMAGE_2", imageProviders.first().providerCode.uppercase())
        assertFalse(imageProviders.any { it.providerCode.contains("imagen", ignoreCase = true) })
    }

    @Test
    fun testTelegramInputRoutesToConfiguredFallbackPriorityProvider() = runBlocking {
        val router = ModelRouter(
            config = AppConfig(environment = "production"),
            providerRepo = providerRepo,
            customProviders = mapOf(
                "openrouter" to mockOpenRouterClient,
                "groq" to mockGroqClient,
                "deepseek" to mockDeepSeekClient,
                "anthropic" to mockAnthropicClient,
                "gemini" to mockGeminiClient
            )
        )

        // Critical Point 4: Input Telegram (Fase 82)
        val gateway = ChannelGateway(modelRouter = router)
        val outbound = gateway.processInbound(
            InboundMessage(
                tenantId = "tenant-test-telegram",
                channelType = "TELEGRAM",
                senderId = "tg-user-12345",
                text = "Bagaimana cara melakukan upgrade paket enterprise?"
            )
        )

        assertNotNull(outbound)
        assertFalse(executionLog.contains("GEMINI"), "Input Telegram must NEVER invoke Gemini")
        assertTrue(executionLog.contains("OPENROUTER") || executionLog.contains("GROQ"))
        assertTrue(outbound!!.text.contains("OpenRouter") || outbound.text.contains("Groq"))
    }

    @Test
    fun testWhatsAppInputRoutesToConfiguredFallbackPriorityProvider() = runBlocking {
        val router = ModelRouter(
            config = AppConfig(environment = "production"),
            providerRepo = providerRepo,
            customProviders = mapOf(
                "openrouter" to mockOpenRouterClient,
                "groq" to mockGroqClient,
                "deepseek" to mockDeepSeekClient,
                "anthropic" to mockAnthropicClient,
                "gemini" to mockGeminiClient
            )
        )

        // Critical Point 5: Input WhatsApp (Fase 82)
        val gateway = ChannelGateway(modelRouter = router)
        val outbound = gateway.processInbound(
            InboundMessage(
                tenantId = "tenant-test-whatsapp",
                channelType = "WHATSAPP",
                senderId = "6281234567890",
                text = "Mohon konfirmasi status onboarding tim marketing kami."
            )
        )

        assertNotNull(outbound)
        assertFalse(executionLog.contains("GEMINI"), "Input WhatsApp must NEVER invoke Gemini")
        assertTrue(executionLog.contains("OPENROUTER") || executionLog.contains("GROQ"))
        assertTrue(outbound!!.text.contains("OpenRouter") || outbound.text.contains("Groq"))
    }

    @Test
    fun testFallbackChainExecutesInOrderWhenPrimaryFails() = runBlocking {
        val failingOpenRouter = object : LlmClient {
            override val providerId = "openrouter"
            override val providerName = "OpenRouter"
            override suspend fun complete(request: LlmRequest): Result<LlmResponse> {
                executionLog.add("OPENROUTER_FAILED")
                return Result.failure(RuntimeException("OpenRouter 503 Service Unavailable"))
            }
        }

        val router = ModelRouter(
            config = AppConfig(environment = "production"),
            providerRepo = providerRepo,
            customProviders = mapOf(
                "openrouter" to failingOpenRouter,
                "groq" to mockGroqClient,
                "deepseek" to mockDeepSeekClient,
                "anthropic" to mockAnthropicClient,
                "gemini" to mockGeminiClient
            )
        )

        val res = router.route(
            ModelRouteRequest(
                taskCategory = "GENERAL_CHAT",
                prompt = "Analisis kinerja keuangan kuartal 3 untuk seluruh divisi korporat secara komprehensif mencakup pendapatan operasional, laba bersih sebelum pajak, arus kas bebas, dan rasio solvabilitas jangka panjang secara mendalam dan terstruktur.",
                tenantId = "tenant-fallback-test"
            )
        )

        assertTrue(res.isSuccess)
        val resp = res.getOrThrow()

        // Must have failed on OpenRouter and fallen back to GROQ (fallback_priority 2)
        assertEquals(listOf("OPENROUTER_FAILED", "OPENROUTER_FAILED", "GROQ"), executionLog)
        assertEquals("groq", resp.providerUsed.lowercase())
        assertFalse(executionLog.contains("GEMINI"), "Fallback chain must not skip to Gemini when Groq is available")

        // Verify usage log in AnalyticsRepository
        val usageLogs = AnalyticsRepository.defaultInstance.getRecentLlmUsageLogs()
        val latestLog = usageLogs.lastOrNull { it.tenantId == "tenant-fallback-test" }
        assertNotNull(latestLog, "Usage log must be recorded in AnalyticsRepository")
        assertEquals("GROQ", latestLog!!.provider)
    }
}
